type SVGObjectPropertyNames =
  "_id" |
  "name" |
  "tagName" |
  "class" |
  "items" |
  "fill" |
  "fillOpacity" |
  "fillRule" |
  "filter" |
  "mask" |
  "opacity" |
  "stroke" |
  "strokeOpacity" |
  "strokeWidth" |
  "strokeDashArray" |
  "strokeDashOffset" |
  "strokeLineCap" |
  "strokeLineJoin" |
  "strokeMiterlimit" |
  "transform" |
  "vectorEffect" |
  "visibility" |
  "cx" |
  "cy" |
  "r" |
  "rx" |
  "ry" |
  "pathLength" |
  "x" |
  "y" |
  "width" |
  "height" |
  "x1" |
  "x2" |
  "y1" |
  "y2" |
  "dx" |
  "dy" |
  "rotate" |
  "lengthAdjust" |
  "textLength" |
  "fontFamily" |
  "fontSize" |
  "fontSizeAdjust" |
  "fontStretch" |
  "fontStyle" |
  "fontVariant" |
  "fontWeight" |
  "text";
export const SVGObjectPropertyMap: Record<SVGObjectPropertyNames, string> = {
  _id: '_id',
  name: 'name',
  tagName: 'tag',
  class: 'class',
  items: 'items',
  fill: 'fill',
  fillOpacity: 'fill-opacity',
  fillRule: 'fill-rule',
  filter: 'filter',
  mask: 'mask',
  opacity: 'opacity',
  stroke: 'stroke',
  strokeOpacity: 'stroke-opacity',
  strokeWidth: 'stroke-width',
  strokeDashArray: 'stroke-dash-array',
  strokeDashOffset: 'stroke-dash-offset',
  strokeLineCap: 'stroke-line-cap',
  strokeLineJoin: 'stroke-line-join',
  strokeMiterlimit: 'stroke-miter-limit',
  transform: 'transform',
  vectorEffect: 'vector-effect',
  visibility: 'visibility',
  cx: 'cx',
  cy: 'cy',
  r: 'r',
  rx: 'rx',
  ry: 'ry',
  pathLength: 'path-length',
  x: 'x',
  y: 'y',
  width: 'width',
  height: 'height',
  x1: 'x1',
  x2: 'x2',
  y1: 'y1',
  y2: 'y2',
  dx: 'dx',
  dy: 'dy',
  rotate: 'rotate',
  lengthAdjust: 'length-adjust',
  textLength: 'text-length',
  fontFamily: 'font-family',
  fontSize: 'font-size',
  fontSizeAdjust: 'font-size-adjust',
  fontStretch: 'font-stretch',
  fontStyle: 'font-style',
  fontVariant: 'font-variant',
  fontWeight: 'font-weight',
  text: 'text'
};